device: 
  name: Frontdoor
  version: 1.0
  on_init:
   - action: led
     values:
       topic: set_color
       payload: blue

variables:
  name: frontdoor
  baresip_base: "/home/interkom/{{id(app).variables.name}}/baresip"

platforms:
- platform: plugins.mqtt
  id: mqtt
  variables:
    base_topic: "home/{{id(app).variables.name}}"
  host: home
  port: 1883
  availability:
    topic: "{{id(mqtt).variables.base_topic}}/connected"
    payload_on: "yes"
    payload_off: "no"

- platform: plugins.gpio
  id: gpio
  factory: rpigpio

- platform: plugins.console
  id: console

- platform: plugins.hass
  id: hass
  connection: mqtt
  exports:
  - id: btn_ring_og
    type: sensor
    on_event: on_hold
    off_event: on_release
    expose_state: state.is_pressed

  - id: btn_ring_eg
    type: sensor
    on_event: on_hold
    off_event: on_release
    expose_state: state.is_pressed     

  - id: playBeep
    type: switch
    payload_on: "ON"
    payload_off: "OFF"    
    on_command: 
    - actions:
       - action: playBeep
         values:
           command: "aplay"
           topic: "aplay"
           payload: "/app/assets/audio/dtmf/cell-phone-1-nr3.wav"
        - action: led
          values: 
            topic: set_color
            payload: green
        - action: delay
          values:
            payload: 2
        - action: led
          values: 
            topic: set_color
            payload: blue            

    off_command:
       - action: playBeep
         values:
           command: "aplay"
           topic: "aplay"
           payload: "/app/assets/audio/dtmf/cell-phone-1-nr3.wav"
        - action: led
          values: 
            topic: set_color
            payload: green
        - action: delay
          values:
            payload: 2
        - action: led
          values: 
            topic: set_color
            payload: blue              
    expose_state: "OFF"
    debug: true
    
    
#- platform: plugins.camera
#  id: camera
#  port: 8091


actions:
- id: delay
  platform: system
  type: DelayAction

- id: print
  platform: console
  type: PrintAction

- id: setVariable
  platform: system
  type: SetVariableAction
  debug: true

- id: led
  platform: gpio
  type: RgbLedAction
  #pin 11
  pin_red: GPIO17
  #pin 13
  pin_green: GPIO27
  #pin 15
  pin_blue: GPIO22
  initial_color: yellow

- id: playBeep
  platform: system
  type: ShellCommandAction
  debug: true

sensors:
- id: btn_ring_eg
  platform: gpio
  debug: true
  #pin18
  pin: GPIO24
  type: ButtonSensor
  #check_state_delay: 0.03
  hold_time: 0.2

- id: btn_ring_og
  platform: gpio
  debug: true
  #pin16
  pin: GPIO23
  type: ButtonSensor
  #check_state_delay: 0.03
  hold_time: 0.2
