device:
  name: Frontdoor
  version: 1.0
  on_init:
   - action: led
     values:
       topic: set_color
       payload: blue

variables:
  name: frontdoor
  baresip_base: "/home/interkom/{{id(app).variables.name}}/baresip"

platforms:
- platform: plugins.mqtt
  id: mqtt
  variables:
    base_topic: "home/{{id(app).variables.name}}"
  host: home
  port: 1883
  availability:
    topic: "{{id(mqtt).variables.base_topic}}/connected"
    payload_on: "yes"
    payload_off: "no"

- platform: plugins.gpio
  id: gpio
  factory: rpigpio

- platform: plugins.console
  id: console

- platform: plugins.hass
  id: hass
  connection: mqtt
  exports:
  - id: btn_ring_og
    type: sensor
    on_event: on_hold
    off_event: on_release
    expose_state: state.is_pressed

  - id: btn_ring_eg
    type: sensor
    on_event: on_hold
    off_event: on_release
    expose_state: state.is_pressed        


actions:
- id: print
  platform: console
  type: PrintAction

- id: setVariable
  platform: system
  type: SetVariableAction
  debug: true

- id: led
  platform: gpio
  type: RgbLedAction
  #pin 11
  pin_red: GPIO17
  #pin 13
  pin_green: GPIO27
  #pin 15
  pin_blue: GPIO22
  initial_color: yellow

sensors:
- id: btn_ring_eg
  platform: gpio
  debug: true
  #pin18
  pin: GPIO24
  type: ButtonSensor
  #check_state_delay: 0.03
  hold_time: 0.2

- id: btn_ring_og
  platform: gpio
  debug: true
  #pin16
  pin: GPIO23
  type: ButtonSensor
  #check_state_delay: 0.03
  hold_time: 0.2
